server:
  port: 8080
  servlet:
    context-path: /
spring:
  jpa:
    database: h2
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    name: oms-auth
    initialization-mode: always
    url: jdbc:h2:mem:simplecheckout
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
  mvc:
    favicon:
      enabled: false
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: debug
debug: false
